import 'package:flame_audio/flame_audio.dart';
import 'package:flutter/foundation.dart';

import 'settings_service.dart';

/// Every sound effect. Files live in `assets/audio/sfx/` (generated by `tools/generate_audio.py`;
/// drop a same-named file in to replace one). [voices] = how many can overlap.
enum Sfx {
  coin('coin', voices: 4, volume: 0.55),
  meat('meat', voices: 2),
  broccoli('broccoli', voices: 2),
  hit('hit', voices: 2),
  shieldBlock('shield_block', voices: 2),
  shieldGraze('shield_graze', voices: 2, volume: 0.7),
  evolve('evolve'),
  devolve('devolve', volume: 0.8),
  swoosh('swoosh', voices: 2, volume: 0.45),
  finish('finish'),
  fight('fight', volume: 0.9),
  victory('victory'),
  defeat('defeat'),
  tap('tap', voices: 2, volume: 0.6),
  buy('buy'),
  star('star', voices: 3, volume: 0.8);

  const Sfx(this.file, {this.voices = 1, this.volume = 1});

  final String file;
  final int voices;
  final double volume;

  String get path => 'sfx/$file.ogg';
}

/// Plays SFX through low-latency pools and one looping music track. Honours the Sound and Music
/// settings. Audio failures are logged and swallowed: the game never depends on sound working.
class AudioService {
  AudioService(this._settings);

  final SettingsService _settings;
  final _pools = <Sfx, AudioPool>{};
  bool _ready = false;
  bool _ducked = false;

  static const _musicFile = 'music/run_loop.ogg';
  static const _musicVolume = 0.45;
  static const _duckedVolume = 0.15;

  Future<void> init() async {
    try {
      FlameAudio.updatePrefix('assets/audio/');
      await FlameAudio.bgm.initialize();
      await Future.wait([
        for (final s in Sfx.values)
          FlameAudio.createPool(s.path, maxPlayers: s.voices).then((p) => _pools[s] = p),
      ]);
      _ready = true;
      _settings.music.addListener(_syncMusic);
      await _syncMusic();
    } catch (e) {
      debugPrint('Audio disabled: $e');
    }
  }

  void play(Sfx s, {double volume = 1}) {
    if (!_ready || !_settings.sound.value) return;
    _pools[s]?.start(volume: (s.volume * volume).clamp(0, 1)).catchError((Object e) {
      debugPrint('Sfx ${s.name} failed: $e');
      return () async {};
    });
  }

  /// Quieter music while a pause or dialog is up.
  void duckMusic(bool duck) {
    if (_ducked == duck) return;
    _ducked = duck;
    if (_ready && FlameAudio.bgm.isPlaying) {
      FlameAudio.bgm.audioPlayer.setVolume(duck ? _duckedVolume : _musicVolume);
    }
  }

  Future<void> _syncMusic() async {
    try {
      final bgm = FlameAudio.bgm;
      if (_settings.music.value && !bgm.isPlaying) {
        await bgm.play(_musicFile, volume: _ducked ? _duckedVolume : _musicVolume);
      } else if (!_settings.music.value && bgm.isPlaying) {
        await bgm.stop();
      }
    } catch (e) {
      debugPrint('Music failed: $e');
    }
  }
}
